spring:
  session:
  datasource:
    url: jdbc:h2:mem:test,MODE=MYSQL
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
          auto: create
        format_sql: true
        show_sql: false
        use_sql_comments: false
  data:
    jpa:
      repositories:
        enabled: true

