spring:
  session:
  datasource:
    url: jdbc:h2:mem:test,MODE=MYSQL
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
          auto: create
        format_sql: true
        show_sql: true
        use_sql_comments: true
  data:
    jpa:
      repositories:
        enabled: true

